{
    'name': 'hospital pactice',
    'version': '1.0',
    'license': 'LGPL-3',
    'depends': ['base', 'ohmanegment', 'sale'],
    'author': 'practice',
    'category': 'Tools',
    'summary': 'Simple practice project',
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/menu.xml',
        'views/InheritField.xml',
        'views/inherite_sale_order_view.xml',
        'views/doctor_views.xml',
        'views/specialization_doctor.xml',
        'views/patient_appointment.xml',
    ],
    'installable': True,
    'application': True,
}
